# Generated by Django 5.0.3 on 2024-04-05 08:06

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='bg_img',
            field=models.ImageField(upload_to='imges/%y/%m/%d', validators=[Blog.models.validate_image_dimensions]),
        ),
    ]
