# Generated by Django 5.0.3 on 2024-04-05 09:25

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_homepage_bg_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=250)),
                ('bg_img', models.ImageField(upload_to='imges/%y/%m/%d', validators=[Blog.models.validate_image_dimensions])),
                ('created_ad', models.DateField(auto_now=True)),
                ('updated_ad', models.DateField(auto_now=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=250)),
                ('bg_img', models.ImageField(upload_to='imges/%y/%m/%d', validators=[Blog.models.validate_image_dimensions])),
                ('created_ad', models.DateField(auto_now=True)),
                ('updated_ad', models.DateField(auto_now=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=250)),
                ('bg_img', models.ImageField(upload_to='imges/%y/%m/%d', validators=[Blog.models.validate_image_dimensions])),
                ('created_ad', models.DateField(auto_now=True)),
                ('updated_ad', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
    ]
