# Generated by Django 5.0.3 on 2024-04-07 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_aboutpage_contactpage_postpage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('bg_img', models.ImageField(upload_to='imges/%y/%m/%d/%bg_img')),
                ('post_img', models.ImageField(upload_to='imges/%y/%m/%d/%post_img')),
                ('created_ad', models.DateField(auto_now=True)),
                ('updated_ad', models.DateField(auto_now=True)),
                ('publish', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PostPage',
        ),
    ]
